version: "3.9"

x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
  AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW_FERNET_KEY}"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow"
  AIRFLOW_UID: "50000"
  AIRFLOW_CONN_POSTGRES_1: "${AIRFLOW_CONN_POSTGRES_1}"
  AIRFLOW_CONN_POSTGRES_2: "${AIRFLOW_CONN_POSTGRES_2}"
  OER_APP_ID: "${OER_APP_ID}"
  _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-postgres psycopg2-binary requests faker python-dotenv"

services:
  postgres-1:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    volumes:
      - pg1_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d db1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  postgres-2:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: db2
    ports:
      - "5434:5432"
    volumes:
      - pg2_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d db2"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  airflow-db:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow-init:
    image: apache/airflow:2.9.3
    environment:
      <<: *airflow-env
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        mkdir -p /opt/airflow/dags /opt/airflow/logs /opt/airflow/plugins
        airflow db migrate
        airflow users create \
        --username admin \
        --password admin \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
    depends_on:
      airflow-db:
        condition: service_healthy
      postgres-1:
        condition: service_healthy
      postgres-2:
        condition: service_healthy

  airflow-webserver:
    image: apache/airflow:2.9.3
    environment:
      <<: *airflow-env
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-db:
        condition: service_healthy

  airflow-scheduler:
    image: apache/airflow:2.9.3
    environment:
      <<: *airflow-env
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-db:
        condition: service_healthy

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres-1
    depends_on:
      - postgres-1

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres-1
      - postgres-2

volumes:
  pg1_data:
  pg2_data:
  airflow_db_data: